### ISSUE TITLE
Upload serialization unsupported when using AWS S3 when add schema.graphql in config setup

### ISSUE THREAD

**Issue by ptthien1012** [parse-community/parse-server-s3-adapter#110]
My project is using Graphql, parse server and parse server cloud code. Im using AWS S3 to upload Images by using filesAdapter with module @parse/s3-files-adapter and it work perfect. But My project using some custom mutation so I need to add custom file Schema.graphql like this in config file of parse server.
Code like this: “graphQLSchema”: “./schema.graphql”.
Then I test to using Mutation upload file it don’t work like usual and it show the error like this.(BTW I’m using FireCamp, it’s a tool to help me write graphql code easier).
![image](https://user-images.githubusercontent.com/67034592/95559773-7b702b00-0a42-11eb-9569-d75fe9b33ec5.png)

This is a code of Schema.graphql

# Type declare
type SendVerificationCodePayload {
  clientMutationId: String
  status: Int!
  messages: String!
}
type ConfirmVerificationCodePayload {
  clientMutationId: String
  status: Int!
  messages: String!
  data: User!
}
type User {
  objectId: String!
  phoneNumber: String!
}

type checkrCandidatesPayload {
  messages: String!
}
# Input declare

input sendVerificationCodeInput {
  "Phone Number"
  phoneNumber: String!
  clientMutationId: String
}
input confirmVerificationCodeInput {
  "Phone Number"
  phoneNumber: String!
  "Verify Code"
  verifyCode: String!
  clientMutationId: String!
}
input checkrCandidatesInput {
  phone: String!
}
extend type Mutation {
  "Send Verify code to login or register"
  createSendVerificationCode(
    input: sendVerificationCodeInput
  ): SendVerificationCodePayload @resolve(to: "sendVerificationCode")
  "Send Verify code to login or register"
  createConfirmVerificationCode(
    input: confirmVerificationCodeInput
  ): ConfirmVerificationCodePayload @resolve(to: "confirmVerificationCode")
  createCheckrCandidates(input: checkrCandidatesInput): checkrCandidatesPayload
    @resolve(to: "checkrCandidates")
}

**Comment by davimacedo** [comment]
I believe you should open this issue in the Parse Server repo: https://github.com/parse-community/parse-server
