### ISSUE TITLE
Dependency on the Parse SDK is unnecessary

### ISSUE THREAD

**Issue by danielsanfr** [parse-community/parse-server-s3-adapter#121]
Hello.

Why does this project depend on the parse SDK if it is not used for anything? I think we could move it to that `devDependencies`.

**Comment by davimacedo** [comment]
Yes. You're right. It is only used for tests and we cam move it to the `devDependencies`. Do you mind to open a PR?

**Comment by danielsanfr** [comment]
Yes, I'll do it right now!

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server-s3-adapter/pull/124
