### ISSUE TITLE
Is this adapter possible to be used with minio?

### ISSUE THREAD

**Issue by mrvnklm** [parse-community/parse-server-s3-adapter#133]
If I change the endpoint it always tries to connect to `BUCKETNAME.s3.myserver.com` instead of `s3.myserver.com`

**Comment by mrvnklm** [comment]
Just found the solution using:

`
s3overrides: {
        endpoint: 'https://s3.myserver.com',
         s3ForcePathStyle: true
      }
`

Maybe this could be mentioned in the docs? It took me about half an hour to find out if this could even work.

**Comment by mtrezza** [comment]
Please feel free to suggest a change for the docs repository if you think this could help others.
