### ISSUE TITLE
Some S3 compatible storages don't support tags

### ISSUE THREAD

**Issue by sarsonj** [parse-community/parse-server-s3-adapter#134]
We are using Digital Ocean spaces and they don't support tags. The API simply returns error when there are tags in file upload request. So that this file adapter don't work with Digital Ocean spaces now.

What I suggest is to send tags only when tags are actually presented in file options. It should be safe - when somebody wants to use tags in their project, it has to use storage with tags support. And from the other way - it has no benefit to send empty `tags` dictionary to the S3.

I created pull request, that handles this.

**Comment by sarsonj** [comment]
Pull request #135

**Comment by sarsonj** [comment]
Related issue in Parse Server repo: https://github.com/parse-community/parse-server/issues/7129

**Comment by mtrezza** [comment]
This should be fixed by https://github.com/parse-community/parse-server/pull/7300
