### ISSUE TITLE
Error uploading file to digital ocean spaces

### ISSUE THREAD

**Issue by KAIOAVILA** [parse-community/parse-server-s3-adapter#137]
I was trying to upload a file to digital ocean spaces and every time it displays the following error, after several attempts and logs, I ended up discovering that digital ocean spaces does not accept the x-amz-tagging header, so to get around this problem I added a option to address this problem.

`error: Error creating a file:  {"code":"InvalidArgument","region":null,"time":"2021-01-24T03:40:07.704Z","requestId":"tx0000000000000c423031d-00600cec17-47cdf09-nyc3b","statusCode":400,"retryable":false,"retryDelay":41.84567606709386,"stack":"InvalidArgument: null\n    at Request.extractError (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/services/s3.js:837:35)\n    at Request.callListeners (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:688:14)\n    at Request.transition (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:690:12)\n    at Request.callListeners (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:688:14)\n    at Request.transition (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:690:12)\n    at Request.callListeners (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at callNextListener (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/event_listeners.js:313:13)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:466:23)"}`

**Comment by KAIOAVILA** [comment]
This PR fix error

#138

**Comment by mtrezza** [comment]
Thanks for reporting.

Can you give more details how this issue is related to https://github.com/parse-community/parse-server-s3-adapter/issues/134? Is this issue a duplicate?

**Comment by KAIOAVILA** [comment]
I understand, I hadn't seen that this issue was open already, I'll close this one and see the other one
