### ISSUE TITLE
Multiple bucket and folder support

### ISSUE THREAD

**Issue by stevestencil** [parse-community/parse-server-s3-adapter#171]
I have modified this adapter so that I can add url params to the file name to dictate which bucket and folder a file should be stored in. For example `image.png?bucket=foo&folder=bar` would store a file called `image.png` in the `bar` folder of the `foo` bucket. This allows me for example to modify the file name in the `beforeSaveFile` hook so that I can have each users files separated into folders and/or buckets. If there is an interest in adding this functionality i'd be happy to submit a PR

**Comment by mtrezza** [comment]
Not sure what the scope of the suggested change is; so please feel free to open a PR to maybe get a better understanding.

**Comment by mtrezza** [comment]
I'm closing this since the scope and purpose of this feature has not been clarified, and there hasn't been any further activity.
