### ISSUE TITLE
Add Parse Server integration tests

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server-s3-adapter#222]
### Issue

There are no end-to-end tests for Parse Server adapters. Instead there is a repo that adds some weak conformance tests:

https://github.com/parse-community/parse-server-s3-adapter/blob/0e0d721b60f15765069414230f237bda56af315e/package.json#L45C6-L45C45

See [conformance tests](https://github.com/parse-community/parse-server-conformance-tests/blob/main/specs/files.js).

### Suggestion

- Add Parse Server integration tests to properly test whether the adapter conforms to the Parse Server interface
- Remove conformance tests

There are Parse Platform repositories that have integration tests which could be used as a guideline on how to set up Parse Server. See for example the Parse JS SDK - it may not have the cleanest implementation, but is a good starting point.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/parse-server-s3-adapter/releases/tag/4.0.0)
