### ISSUE TITLE
file upload progressBar callback

### ISSUE THREAD

**Issue by navin10sharma** [parse-community/parse-server-s3-adapter#25]
Hello Guys

I  am using this adapter in parse server to upload and it works absolutely fine but i want to integrate progress Bar with file upload but i did't find is this functionality available in this module or not because. i didn't get any callback during upload. i am using Rest API in my project.

Thanks

**Comment by dplewis** [comment]
This has been added in the JS SDK 2.2.0 (Browser only)

https://github.com/parse-community/Parse-SDK-JS/pull/373
