### ISSUE TITLE
Pass S3Override as environmental variable

### ISSUE THREAD

**Issue by mrmarcsmith** [parse-community/parse-server-s3-adapter#36]
We use docker to spin up our parse servers, that leaves environmental variables as the cleanest way to pass information along. Is there a way to pass "s3OverrideOptions" as an environmental variable? if not, that would be an incredible feature for me.

**Comment by acinader** [comment]
we'd need some form of translation between json object format and the string format that works for env vars.  see #40 for more details.  

I'm glad to review any pr

**Comment by acinader** [comment]
fixed by #50
