### ISSUE TITLE
fix lint to catch whitespace problems

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-server-s3-adapter#53]
things like `foo ,bar`, `if(x)`, and other white space issues should get caught by lint.

**Comment by dplewis** [comment]
@acinader You could use [airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base) but that a lot of linter changes would have to be made.

Or we could build the eslintrc.json file with `keyword-spacing` and `comma-spacing`

**Comment by acinader** [comment]
I think bringing it into airbnb-base conformance would be ideal.  No recollection of how big a deal that would be though...not sure that just adding one rules one by one is any better than the status quo...
