### ISSUE TITLE
credentials are null when deployed on remote server, has values on local server

### ISSUE THREAD

**Issue by pwax** [parse-community/parse-server-s3-adapter#57]
I'm setting up the S3 adapter, and I have an issue using this adapter when deployed to my Heroku server. The issue is that credentials are null on the s3 adapter object.

Running parse server 2.7.1, s3-files-adaper 1.2.1

Here's my api configuration: 
```
//s3
var s3Options = {
	bucket:process.env.S3_BUCKET,
	region:'xxx',
	ServerSideEncryption: 'AES256'
}
var s3Adapter = new S3Adapter(s3Options);
console.log(JSON.stringify(s3Adapter, null, 2))

//api
var masterKey = process.env.MASTER_KEY || 'xxxx'
var clientKey = process.env.CLIENT_KEY || 'xxx'
var appId = process.env.APP_ID || 'xxx'
var javascriptKey = process.env.JAVASCRIPT_KEY || 'xxx'
var serverURL = process.env.SERVER_URL || 'xxx'
var publicServerURL = process.env.PUBLIC_SERVER_URL || 'xxx'
var api = new ParseServer({
	databaseURI: process.env.MONGO_URI || 'xxx',
	cloud: xxx,
	appId: appId,
	clientKey: clientKey,
	javascriptKey: javascriptKey,
	fileKey: process.env.FILE_KEY,
	masterKey: masterKey,
	serverURL: serverURL,
	publicServerURL: publicServerURL,
	filesAdapter: s3Adapter,
	auth: {
		facebook: {
			appIds: ["xxx"]
		}
	},
	facebookAppIds:["xxx"]
})
...
```
If I'm understanding the docs correctly, then setting the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` should be enough for the S3 configuration. I've set both of these values locally (using a .env file with dotenv) and in my config vars on Heroku. 

When I log `s3Adapter` locally (notice that credentials have values):
```
{
  "_region": "xxx",
  "_bucket": "xxx",
  "_bucketPrefix": "",
  "_directAccess": xxx,
  "_baseUrl": null,
  "_baseUrlDirect": false,
  "_signatureVersion": "v4",
  "_globalCacheControl": null,
  "_encryption": "AES256",
  "_s3Client": {
    "config": {
      "credentials": {
        "expired": false,
        "expireTime": null,
        "accessKeyId": "xxx",
        "profile": "default",
        "disableAssumeRole": true
      },
...
```
and when I log `s3Adapter` after deploying to Heroku (notice null for config):
```
{
  "_region": "xxx",
  "_bucket": "xxx",
  "_bucketPrefix": "",
  "_directAccess": xxx,
  "_baseUrl": null,
  "_baseUrlDirect": false,
  "_signatureVersion": "v4",
  "_globalCacheControl": null,
  "_encryption": "AES256",
  "_s3Client": {
    "config": {
      "credentials": null,
  ...
```
I've tried not using dotenv when deployed to Heroku as I thought that might mess with the config, but that didn't yield any results. I was unable to track down this specific problem for some time since the only error log I was getting a 130 couldn't save file error. I finally got a different error message after some tinkering:

` {"message":"Missing credentials in config","stack":"CredentialsError: Missing credentials in config\n    at ClientRequest.<anonymous> (/app/node_modules/aws-sdk/lib/http/node.js:83:34)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at ClientRequest.emit (events.js:208:7)\n    at Socket.emitTimeout (_http_client.js:708:34)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at Socket.emit (events.js:208:7)\n    at Socket._onTimeout (net.js:407:8)\n    at ontimeout (timers.js:475:11)","code":"CredentialsError","name":"CredentialsError","time":"2018-01-21T08:12:13.062Z","retryable":true,"originalError":{"message":"Could not load credentials from any providers","code":"CredentialsError","time":"2018-01-21T08:12:13.062Z","retryable":true,"originalError":{"message":"Connection timed out after 1000ms","code":"TimeoutError","time":"2018-01-21T08:12:13.062Z","retryable":true}},"level":"error"}`

This error led me to log the s3 adapter object to find null credentials. For all I know, this could be intended behavior. Regardless, I haven't been able to get this adaptor working when deployed to Heroku. 

Thanks!

**Comment by acinader** [comment]
this is old and almost certainly a configuration issue vs a bug.  closing for now, feel free to re-open if it is an issue.
