### ISSUE TITLE
AWS switching to longer id's

### ISSUE THREAD

**Issue by chrisfoulds** [parse-community/parse-server-s3-adapter#58]
I am sure everyone has had this email (See below) , does this adapter support them ?

-----

Dear Amazon Web Services Customer,

In less than 60 days, Amazon EC2, Amazon EBS, and AWS Storage Gateway are migrating to longer format resource IDs to support the ongoing growth of Amazon Web Services as announced back in December 2017. You can click on “Switch to longer IDs” in the AWS Management Console or use the APIs to receive longer IDs today.

Systems that parse or store resource IDs may not work with longer IDs. We strongly recommend that you test your systems interoperability with longer IDs. After June 2018, all new resources will receive longer IDs. We will continue to support shorter IDs for existing resources.

Additional information, including details of how to test your systems, can be found in the FAQs and docs. Please contact the AWS support team on the community forums or via AWS Premium Support if you have questions. Click below to switch to longer IDs now.

**Comment by flovilmart** [comment]
Can you follow the instructions and perhaps see if there’s an issue with a demo app (not your prod one)? If there is, please open an issue describing the problem?
