### ISSUE TITLE
Presigned URLs

### ISSUE THREAD

**Issue by chrisbyers** [parse-community/parse-server-s3-adapter#78]
This is a feature suggestion/request.  It would be nice to be able to retrieve a presigned URL with dynamic expiration from the Amazon S3 bucket when directAccess is enabled.  This would allow more security by allowing us to lock down the S3 bucket with public access turned off, and still provide the benefit of not proxy'ing the download through the parse server.

**Comment by dplewis** [comment]
Hi @chrisbyers,

Would this be something you would like to work on?

**Comment by danielsanfr** [comment]
Hi. I think this is an important thing to be implemented.
Can anyone tell me where to find the information so I can try to implement this?

**Comment by davimacedo** [comment]
I believe we'd need to change this method: https://github.com/parse-community/parse-server-s3-adapter/blob/master/index.js#L159

**Comment by mtrezza** [comment]
Closing via #180
