### ISSUE TITLE
Customize ACL

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server-s3-adapter#89]
### Issue

The adapter parameter `directAccess` currently influences
- the ACL when writing a file to the S3 bucket
https://github.com/parse-community/parse-server-s3-adapter/blob/5bbc7fad73703aa492a9a2b563e4f2126378b9e3/index.js#L89-L91

- the file path when composing the URL of a requested Parse.File
https://github.com/parse-community/parse-server-s3-adapter/blob/5bbc7fad73703aa492a9a2b563e4f2126378b9e3/index.js#L155-L163

This parameter therefore controls two aspects that have nothing to do with each other.

Specifically, the ACL of a file put into the S3 bucket depends on the ACL management in that specific architecture. For example, regardless of the ACL of a file, the bucket itself has an ACL, the AWS IAM users and roles have ACLs.

On the other hand, when using a CDN, the file URL needs to have the base URL of the CDN. But without setting `directAccess: true`, the base URL cannot be set and the URL always starts with the parse server mount path:
https://github.com/parse-community/parse-server-s3-adapter/blob/5bbc7fad73703aa492a9a2b563e4f2126378b9e3/index.js#L163

### Solutions

There should be separate adapter parameters for
- the file ACL to set when writing a file
- the base URL to return when composing the file URL

The easiest way would be to simply add an optional `acl` parameter that allows to define the ACL to be set when writing the file. Let it default to `public-read` and it won't even be a breaking change.

**Comment by mtrezza** [comment]
@dplewis Do you know how to run the tests locally? There isn't a contribution guide.

**Comment by dplewis** [comment]
npm run test should do it

**Comment by mtrezza** [comment]
Thanks, I forgot to run npm install 🤦‍♂️
